//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBibliaTec.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Formulars = new HashSet<Formular>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string FAuthor { get; set; }
        public string NAuthor { get; set; }
        public string OAuthor { get; set; }
        public Nullable<int> Genre { get; set; }
        public string Count { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<System.DateTime> Date_Vipusk { get; set; }
        public byte[] ImageBook { get; set; }
    
        public virtual Category Category1 { get; set; }
        public virtual Genre Genre1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Formular> Formulars { get; set; }
    }
}
