//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBibliaTec.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formular
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Formular()
        {
            this.Books = new HashSet<Book>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_Clients { get; set; }
        public Nullable<int> ID_Personals { get; set; }
        public Nullable<System.DateTime> Date_Vidachi { get; set; }
        public Nullable<System.DateTime> Date_Sdachi { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Personal Personal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book> Books { get; set; }
    }
}
