//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBibliaTec.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Izdatel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Izdatel()
        {
            this.Books = new HashSet<Book>();
        }
    
        public int ID { get; set; }
        public string Name_izdat { get; set; }
        public string Phone { get; set; }
        public string Adress { get; set; }
        public Nullable<int> VidIzdatel { get; set; }
        public Nullable<int> ClassificIzdat { get; set; }
        public Nullable<int> VidDeitIzdat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book> Books { get; set; }
        public virtual ClassificIzdat ClassificIzdat1 { get; set; }
        public virtual VidDeitIzdat VidDeitIzdat1 { get; set; }
        public virtual VidIzdat VidIzdat { get; set; }
    }
}
